# Generated by Django 4.0.4 on 2022-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_first_name_patient_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
