# Generated by Django 4.0.4 on 2022-12-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_emergency_contact_phone_emergencycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
