# Generated by Django 4.0.4 on 2023-01-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
